In [23]:
import pandas
import numpy as np
from sklearn import model_selection
from tensorflow import keras
ratings = pandas.read_csv('google_review_ratings.csv', header=0)

In [18]:
ratings.head(10)

User  Category 1  Category 2  Category 3  Category 4  Category 5  \
0   User 1         0.0         0.0        3.63        3.65         5.0   
1   User 2         0.0         0.0        3.63        3.65         5.0   
2   User 3         0.0         0.0        3.63        3.63         5.0   
3   User 4         0.0         0.5        3.63        3.63         5.0   
4   User 5         0.0         0.0        3.63        3.63         5.0   
5   User 6         0.0         0.0        3.63        3.63         5.0   
6   User 7         0.0         5.0        3.63        3.63         5.0   
7   User 8         0.0         5.0        3.63        3.63         5.0   
8   User 9         0.0         5.0        3.64        3.64         5.0   
9  User 10         0.0         5.0        3.64        3.64         5.0   

   Category 6  Category 7  Category 8  Category 9  ...  Category 15  \
0        2.92        5.00        2.35        2.33  ...         1.74   
1        2.92        5.00        2.64        2.33  ...         1.74   
2        2.92        5.00        2.64        2.33  ...         1.74   
3        2.92        5.00        2.35        2.33  ...         1.74   
4        2.92        5.00        2.64        2.33  ...         1.74   
5        2.92        5.00        2.63        2.33  ...         1.74   
6        2.92        3.03        2.35        2.33  ...         1.75   
7        2.92        5.00        2.63        2.33  ...         1.74   
8        2.92        3.03        2.62        2.32  ...         0.75   
9        2.92        5.00        2.35        2.32  ...         0.74   

  Category 16  Category 17  Category 18  Category 19  Category 20  \
0        0.59          0.5          0.0          0.5          0.0   
1        0.59          0.5          0.0          0.5          0.0   
2        0.59          0.5          0.0          0.5          0.0   
3        0.59          0.5          0.0          0.5          0.0   
4        0.59          0.5          0.0          0.5          0.0   
5        0.59          0.5          0.0          0.5          0.0   
6        0.59          0.5          0.0          0.5          0.0   
7        0.60          0.5          0.0          0.5          0.0   
8        0.60          0.0          0.0          0.5          0.0   
9        0.59          0.0          0.0          0.0          0.0   

   Category 21  Category 22  Category 23  Category 24  
0          0.0          0.0          0.0          0.0  
1          0.0          0.0          0.0          0.0  
2          0.0          0.0          0.0          0.0  
3          0.0          0.0          0.0          0.0  
4          0.0          0.0          0.0          0.0  
5          0.0          0.0          0.0          0.0  
6          0.0          0.0          0.0          0.0  
7          0.0          0.0          0.0          0.0  
8          0.0          0.0          0.0          0.0  
9          0.0          0.0          0.0          0.0  

[10 rows x 25 columns]

In [20]:
atributos = ratings.loc[:, 'Category 1':'Category 23']
atributos = atributos.to_numpy()
print(atributos)

[[0.0 0.0 3.63 ... 0.0 0.0 0.0]
 [0.0 0.0 3.63 ... 0.0 0.0 0.0]
 [0.0 0.0 3.63 ... 0.0 0.0 0.0]
 ...
 [0.94 5.0 4.03 ... 1.07 5.0 5.0]
 [0.95 4.05 4.05 ... 1.08 5.0 5.0]
 [0.95 4.07 5.0 ... 1.08 5.0 5.0]]


In [22]:
objetivo = ratings['Category 24']
objetivo = objetivo.to_numpy()
print(objetivo)

[0.   0.   0.   ... 1.11 1.12 1.17]


In [24]:
(atributos_entrenamiento, atributos_prueba,
 objetivo_entrenamiento, objetivo_prueba) = model_selection.train_test_split(
    atributos, objetivo, test_size=.33)

In [25]:
red_ratings = keras.Sequential()
red_ratings.add(keras.Input(shape=(23,)))
red_ratings.add(keras.layers.Dense(1))

In [26]:
red_ratings.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 24        
                                                                 
Total params: 24
Trainable params: 24
Non-trainable params: 0
_________________________________________________________________


In [6]:
#Metodo LIME
import random
from sklearn.linear_model import Ridge



"""
N es el n´umero de permutaciones a realizar
f es el modelo a explicar
X′ ← {} muestras perturbadas
R ← {} representaciones
W ← {} las distancias entre la muestra x y sus perturbaciones
for 1
to
N do
Selecciona k atributos aleatoriamente
x′ ← una perturbaci´on de x donde se perturban los k atributos anteriores.
w ← la distancia entre x y x′
r ← la representaci´on de x′ respecto a x
X′ ← X′ ∪ x′
R ← R ∪ r
W ← R ∪ w
end for
Y ′ ← f(X′) las predicciones de las perturbaciones
G ← modelo ridge entrenado con R para predecir Y ′ y ponderando cada
muestra con W
return los par´ametros de G
"""

def explain_model(f, x, N,M):
    #f es el modelo a explicar
    #N es el número de permutaciones a realizar
    Xi = [] #muestras perturbadas
    R = [] #representaciones
    W = [] #Las distancias entre la muestra x y sus pertubaciones
    for i in range(N):
        k = random.randint(1, len(x)) #Escojo un número aletario que representa el número de los atributos a seleccionar
        perturbed_x = x.copy() #copio la muestra original
        for i in range(k): 
            perturbed_attr = random.choice(list(x.keys())) #Voy escojiento los atributos que perturbare de forma aleatoria
            mx = abs(max([a[perturbed_attr] for a in M])) #Para el atributo aletorio seleccionado calculo el valor máximo
            mn = abs(min([a[perturbed_attr] for a in M])) #Para el atributo aletorio seleccionado calculo el valor mínimo
            perturbed_x[perturbed_attr] = random.uniform(mn, mx) # pertubo el atributo con un valor aleatorio ente mn y mx
        w = abs(sum([x[attr] - perturbed_x[attr] for attr in x.keys()])) #Calculo la distancia entre el original y el perturbado
        r = {attr: 0  if x_perturbed[attr] = x[attr] else 1 for attr in x.keys()} #miramos la representacion del pertubado respecto al original utilizando un operador ternario como solemos hacer en java
        Xi.append(x_perturbed) #Acumulo en la lista los perturbados
        R.append(r)#Acumulamos en la lista de representaciones
        W.append(w)#Añadimos las distancias a la lista
    Y_perturbed = f(Xi)#aplicamos el modelo f
    G = Ridge().fit(R, Y_perturbed, sample_weight=W) #Utilizamos Ridge 
    return G.get_params() #Devolvemos los parametros


In [27]:
#METODO IDENTIDAD
import pandas
import numpy as np
from scipy.spatial.distance import cdist
from scipy.stats import pearsonr
from scipy.special import lambertw
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

# Creamos dos instancias de datos y sus respectivas explicaciones LIME
xa = np.array([0.5, 0.7, 0.1, 0.3])
xb = np.array([0.3, 0.9, 0.2, 0.1])
ea = np.array([0.2, 0.3, 0.1, 0.4])
eb = np.array([0.3, 0.4, 0.5, 0.1])

# Calculamos la distancia entre las instancias de datos
data_distance = cdist(xa.reshape(1,-1), xb.reshape(1,-1))

# Calculamos la distancia entre las explicaciones LIME
exp_distance = cdist(ea.reshape(1,-1), eb.reshape(1,-1))

# Verificamos si la métrica Identidad se cumple
if data_distance == 0 and exp_distance != 0:
    print("La métrica Identidad no se cumple para este par de instancias de datos y sus explicaciones LIME correspondientes.")
else:
    print("La métrica Identidad se cumple para este par de instancias de datos y sus explicaciones LIME correspondientes.")


La métrica Identidad se cumple para este par de instancias de datos y sus explicaciones LIME correspondientes.


In [ ]:
#METODO SEPARABILIDAD
# Creamos dos instancias de datos y sus respectivas explicaciones LIME
xa = np.array([0.5, 0.7, 0.1, 0.3])
xb = np.array([0.3, 0.9, 0.2, 0.1])
ea = np.array([0.2, 0.3, 0.1, 0.4])
eb = np.array([0.3, 0.4, 0.5, 0.1])

# Calculamos la distancia entre las instancias de datos
data_distance = cdist(xa.reshape(1,-1), xb.reshape(1,-1))

# Calculamos la distancia entre las explicaciones LIME
exp_distance = cdist(ea.reshape(1,-1), eb.reshape(1,-1))

# Verificamos si la métrica Separabilidad se cumple
if data_distance != 0 and exp_distance <= 0:
    print("La métrica Separabilidad no se cumple para este par de instancias de datos y sus explicaciones LIME correspondientes.")
else:
    print("La métrica Separabilidad se cumple para este par de instancias de datos y sus explicaciones LIME correspondientes.")


In [ ]:
#METODO ESTABILIDAD
# Creamos las instancias de datos y sus respectivas explicaciones LIME
x = np.array([[0.5, 0.7, 0.1, 0.3], [0.3, 0.9, 0.2, 0.1], [0.1, 0.2, 0.8, 0.6]])
ex = np.array([[0.2, 0.3, 0.1, 0.4], [0.3, 0.4, 0.5, 0.1], [0.1, 0.3, 0.6, 0.2]])

# Creamos las distancias entre las instancias de datos y sus respectivas explicaciones LIME
data_distances = cdist(x, x[0].reshape(1,-1))
exp_distances = cdist(ex, ex[0].reshape(1,-1))

# Calculamos el coeficiente de correlación de Pearson entre las distancias
correlation, _ = pearsonr(data_distances.flatten(), exp_distances.flatten())

# Verificamos si la métrica Estabilidad se cumple
if correlation > 0:
    print("La métrica Estabilidad se cumple para este conjunto de instancias de datos y sus explicaciones LIME correspondientes.")
else:
    print("La métrica Estabilidad no se cumple para este conjunto de instancias de datos y sus explicaciones LIME correspondientes.")


In [ ]:
#METODO COHERENCIA
# Creamos las instancias de datos y sus respectivas explicaciones LIME
x = np.array([[0.5, 0.7, 0.1, 0.3], [0.3, 0.9, 0.2, 0.1], [0.1, 0.2, 0.8, 0.6]])
ex = np.array([[0.2, 0.3, 0.1, 0.4], [0.3, 0.4, 0.5, 0.1], [0.1, 0.3, 0.6, 0.2]])

# Calculamos los pesos de las instancias de datos y sus respectivas explicaciones LIME
data_weights = np.exp(-np.linalg.norm(x - x.mean(axis=0), axis=1))
exp_weights = np.exp(-np.linalg.norm(ex - ex.mean(axis=0), axis=1))

# Calculamos los logaritmos naturales de los pesos y los sumamos
log_sum_data = np.sum(np.log(data_weights))
log_sum_exp = np.sum(np.log(exp_weights))

# Calculamos la métrica Coherencia
alpha = np.exp(log_sum_data - log_sum_exp + lambertw(0.0, -np.exp(log_sum_data - log_sum_exp)).real)
alpha /= len(x)

# Imprimimos el valor de la métrica Coherencia
print("El valor de la métrica Coherencia es:", alpha)


In [ ]:
#METODO COMPLETITUD
# Creamos las instancias de datos y sus respectivas explicaciones LIME
x = np.array([[0.5, 0.7, 0.1, 0.3], [0.3, 0.9, 0.2, 0.1], [0.1, 0.2, 0.8, 0.6]])
ex = np.array([[0.2, 0.3, 0.1, 0.4], [0.3, 0.4, 0.5, 0.1], [0.1, 0.3, 0.6, 0.2]])

# Calculamos los pesos de las instancias de datos y sus respectivas explicaciones LIME
data_weights = np.exp(-np.linalg.norm(x - x.mean(axis=0), axis=1))
exp_weights = np.exp(-np.linalg.norm(ex - ex.mean(axis=0), axis=1))

# Calculamos los valores de ei y pi
ei = np.sum(exp_weights)
pi = np.sum(data_weights)

# Calculamos la métrica Completitud
gamma = ei / pi

# Imprimimos el valor de la métrica Completitud
print("El valor de la métrica Completitud es:", gamma)


In [ ]:
#METODO CONGRUENCIA
# Creamos una lista de valores de coherencia para un conjunto de N muestras
alpha_values = [0.8, 0.6, 0.7, 0.9, 0.5]

# Calculamos el valor promedio de la coherencia
alpha = np.mean(alpha_values)

# Creamos una lista de valores de alpha_i para cada instancia de datos
alpha_i_values = [0.9, 0.7, 0.6, 0.8, 0.4]

# Calculamos el número de instancias de datos
N = len(alpha_i_values)

# Calculamos la suma de las diferencias cuadráticas entre alpha_i y alpha
diff_squares_sum = np.sum((np.array(alpha_i_values) - alpha) ** 2)

# Calculamos la métrica Congruencia
delta = np.sqrt((diff_squares_sum / N) / alpha)

# Imprimimos el valor de la métrica Congruencia
print("El valor de la métrica Congruencia es:", delta)


In [ ]:
#METODO SELECTIVIDAD
# Cargamos el dataset de cáncer de mama de scikit-learn
data = load_breast_cancer()

# Definimos las características y la variable objetivo
X = data['data']
y = data['target']

# Creamos un modelo de regresión logística
model = LogisticRegression()

# Entrenamos el modelo
model.fit(X, y)

# Obtenemos las predicciones del modelo en el conjunto de datos completo
y_pred = model.predict_proba(X)[:, 1]

# Calculamos el AUC para el modelo entrenado en el conjunto de datos completo
auc_full = roc_auc_score(y, y_pred)

# Ordenamos las características de más a menos relevantes según el modelo
idx_sorted = np.argsort(np.abs(model.coef_))[0][::-1]

# Creamos una lista para almacenar los AUC para cada característica eliminada
auc_scores = []

# Iteramos sobre las características de más a menos relevantes según el modelo
for i in range(X.shape[1]):
    # Establecemos la característica i en cero
    X_test = X.copy()
    X_test[:, idx_sorted[i]] = 0
    
    # Obtenemos las predicciones del modelo en el conjunto de datos con la característica i eliminada
    y_pred_test = model.predict_proba(X_test)[:, 1]
    
    # Calculamos el AUC para el modelo entrenado en el conjunto de datos con la característica i eliminada
    auc_test = roc_auc_score(y, y_pred_test)
    
    # Almacenamos el AUC para la característica i eliminada en la lista de AUC
    auc_scores.append(auc_test)

# Calculamos la métrica Selectividad como el área bajo la curva ROC para el gráfico de AUC vs características eliminadas
selectivity = np.trapz(auc_scores, dx=1)

# Imprimimos el valor de la métrica Selectividad
print("El valor de la métrica Selectividad es:", selectivity)
