In [6]:
#Importamos las librerias necesarias para crear la red neuronal
import pandas
import numpy as np
from sklearn import model_selection, preprocessing
from tensorflow import keras
#Leemos el csv
evaluation = pandas.read_csv('turkiye-student-evaluation_R_Specific.csv', header=0)

In [7]:
#Mostramos las 10 primeras lineas para ver que se ha leido bién
evaluation.head(10)

instr  class  nb.repeat  attendance  difficulty  Q1  Q2  Q3  Q4  Q5  ...  \
1       1      2          1           0           4   3   3   3   3   3  ...   
2       1      2          1           1           3   3   3   3   3   3  ...   
3       1      2          1           2           4   5   5   5   5   5  ...   
4       1      2          1           1           3   3   3   3   3   3  ...   
5       1      2          1           0           1   1   1   1   1   1  ...   
6       1      2          1           3           3   4   4   4   4   4  ...   
7       1      2          1           1           3   4   4   4   4   4  ...   
8       1      2          1           1           3   5   5   5   5   5  ...   
9       1      2          1           1           3   4   4   4   4   4  ...   
10      1      2          1           4           4   4   4   4   4   4  ...   

    Q19  Q20  Q21  Q22  Q23  Q24  Q25  Q26  Q27  Q28  
1     3    3    3    3    3    3    3    3    3    3  
2     3    3    3    3    3    3    3    3    3    3  
3     5    5    5    5    5    5    5    5    5    5  
4     3    3    3    3    3    3    3    3    3    3  
5     1    1    1    1    1    1    1    1    1    1  
6     4    4    4    4    4    4    4    4    4    4  
7     4    4    4    4    4    4    4    4    4    4  
8     5    5    5    5    5    5    5    5    5    5  
9     4    4    4    4    4    4    4    4    4    4  
10    4    4    4    4    4    4    4    4    4    4  

[10 rows x 33 columns]

In [9]:
#Seleccionamos los atributos 
atributos = evaluation.loc[:, 'class':'Q27']
atributos = atributos.to_numpy()
scaler = preprocessing.MinMaxScaler()
atributos = scaler.fit_transform(atributos)
print(atributos)

[[0.08333333 0.         0.         ... 0.5        0.5        0.5       ]
 [0.08333333 0.         0.25       ... 0.5        0.5        0.5       ]
 [0.08333333 0.         0.5        ... 1.         1.         1.        ]
 ...
 [1.         0.         0.         ... 1.         1.         1.        ]
 [1.         0.         0.25       ... 0.         0.         0.        ]
 [1.         0.         0.25       ... 0.         0.         0.        ]]


In [203]:
objetivo = evaluation['Q28']
objetivo = evaluation['Q28'].to_numpy(dtype=np.float32)
scaler = preprocessing.MinMaxScaler()
objetivo = scaler.fit_transform(objetivo.reshape(-1, 1))
print(objetivo)

[[0.5]
 [0.5]
 [1. ]
 ...
 [1. ]
 [0. ]
 [0. ]]


In [204]:
(atributos_entrenamiento, atributos_prueba,
 objetivo_entrenamiento, objetivo_prueba) = model_selection.train_test_split(
    atributos, objetivo, test_size=.15)

In [205]:
normalizador = keras.layers.Normalization()
normalizador.adapt(atributos_entrenamiento)
red_evaluation = keras.Sequential()
red_evaluation.add(keras.layers.Input(shape=(31,)))
red_evaluation.add(normalizador)
red_evaluation.add(keras.layers.Dense(75, activation='relu'))
red_evaluation.add(keras.layers.Dense(75, activation='sigmoid'))
red_evaluation.add(keras.layers.Dense(1, activation='sigmoid'))
red_evaluation.add(keras.layers.Lambda(lambda x: x * 5))


In [206]:
red_evaluation.summary()

Model: "sequential_34"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 normalization_34 (Normaliza  (None, 31)               63        
 tion)                                                           
                                                                 
 dense_134 (Dense)           (None, 75)                2400      
                                                                 
 dense_135 (Dense)           (None, 75)                5700      
                                                                 
 dense_136 (Dense)           (None, 1)                 76        
                                                                 
 lambda_13 (Lambda)          (None, 1)                 0         
                                                                 
Total params: 8,239
Trainable params: 8,176
Non-trainable params: 63
__________________________________________________

In [207]:

red_evaluation.compile(optimizer='SGD', loss='mean_squared_error', metrics=['accuracy', 'mae'])
red_evaluation.fit(atributos_entrenamiento, objetivo_entrenamiento,
                batch_size=256, epochs=10)

Epoch 1/10
20/20 [==============================] - 0s 1ms/step - loss: 0.2987 - accuracy: 0.2068 - mae: 0.3653
Epoch 2/10
20/20 [==============================] - 0s 997us/step - loss: 0.0638 - accuracy: 0.3151 - mae: 0.2067
Epoch 3/10
20/20 [==============================] - 0s 1ms/step - loss: 0.0527 - accuracy: 0.3186 - mae: 0.1842
Epoch 4/10
20/20 [==============================] - 0s 1ms/step - loss: 0.0452 - accuracy: 0.3208 - mae: 0.1663
Epoch 5/10
20/20 [==============================] - 0s 1ms/step - loss: 0.0399 - accuracy: 0.3208 - mae: 0.1517
Epoch 6/10
20/20 [==============================] - 0s 977us/step - loss: 0.0364 - accuracy: 0.3224 - mae: 0.1405
Epoch 7/10
20/20 [==============================] - 0s 1ms/step - loss: 0.0339 - accuracy: 0.3228 - mae: 0.1320
Epoch 8/10
20/20 [==============================] - 0s 1ms/step - loss: 0.0320 - accuracy: 0.3226 - mae: 0.1256
Epoch 9/10
20/20 [==============================] - 0s 1ms/step - loss: 0.0307 - accuracy: 0.3228 - 

In [208]:
red_evaluation.evaluate(atributos_prueba, objetivo_prueba)

28/28 [==============================] - 0s 713us/step - loss: 0.0305 - accuracy: 0.3333 - mae: 0.1201


[0.030451636761426926, 0.3333333432674408, 0.12010810524225235]

In [10]:
#Importamos las librerias necesarias para crear la red neuronal
import pandas
import numpy as np
from sklearn import model_selection, preprocessing
from tensorflow import keras
#Leemos el csv
#bikes = pandas.read_csv('hour.csv', header=0)
bikes = pandas.read_csv('hour2.csv',header = 0)

# Eliminar la columna
#bikes = bikes.drop('dteday', axis=1)
#bikes = bikes.drop('instant', axis=1)
# Guardar el DataFrame resultante en un nuevo archivo CSV
#bikes.to_csv('hour2.csv', index=False)

In [2]:
#Mostramos las 10 primeras lineas para ver que se ha leido bién
bikes.head(10)

season  yr  mnth  hr  holiday  weekday  workingday  weathersit  temp  \
0       1   0     1   0        0        6           0           1  0.24   
1       1   0     1   1        0        6           0           1  0.22   
2       1   0     1   2        0        6           0           1  0.22   
3       1   0     1   3        0        6           0           1  0.24   
4       1   0     1   4        0        6           0           1  0.24   
5       1   0     1   5        0        6           0           2  0.24   
6       1   0     1   6        0        6           0           1  0.22   
7       1   0     1   7        0        6           0           1  0.20   
8       1   0     1   8        0        6           0           1  0.24   
9       1   0     1   9        0        6           0           1  0.32   

    atemp   hum  windspeed  casual  registered  cnt  
0  0.2879  0.81     0.0000       3          13   16  
1  0.2727  0.80     0.0000       8          32   40  
2  0.2727  0.80     0.0000       5          27   32  
3  0.2879  0.75     0.0000       3          10   13  
4  0.2879  0.75     0.0000       0           1    1  
5  0.2576  0.75     0.0896       0           1    1  
6  0.2727  0.80     0.0000       2           0    2  
7  0.2576  0.86     0.0000       1           2    3  
8  0.2879  0.75     0.0000       1           7    8  
9  0.3485  0.76     0.0000       8           6   14

In [11]:
#Seleccionamos los atributos 
attr = bikes.loc[:, 'season':'registered']
attr = bikes.to_numpy()
scaler = preprocessing.MinMaxScaler()
#attr = scaler.fit_transform(attr)
print(attr)

[[ 1.  0.  1. ...  3. 13. 16.]
 [ 1.  0.  1. ...  8. 32. 40.]
 [ 1.  0.  1. ...  5. 27. 32.]
 ...
 [ 1.  1. 12. ...  7. 83. 90.]
 [ 1.  1. 12. ... 13. 48. 61.]
 [ 1.  1. 12. ... 12. 37. 49.]]


In [228]:
#Seleccionamos los objetivos
obj = bikes['cnt']
obj = bikes['cnt'].to_numpy(dtype=np.float32)
#scaler = preprocessing.MinMaxScaler()
#objetivo = scaler.fit_transform(objetivo.reshape(-1, 1))
print(obj)

[16. 40. 32. ... 90. 61. 49.]


In [229]:
#Cogemos un 85% de los datos para entrenar y un 15% de los datos para evaluar el modelo
(attr_entrenamiento, attr_prueba,
 obj_entrenamiento, obj_prueba) = model_selection.train_test_split(
    attr, obj, test_size=.10)

In [230]:
#Creamos la red neuronal
normalizador = keras.layers.Normalization()
normalizador.adapt(attr_entrenamiento)
red_bikes = keras.Sequential()
red_bikes.add(keras.layers.Input(shape=(15,)))
red_bikes.add(normalizador)
red_bikes.add(keras.layers.Dense(100, activation='sigmoid'))
red_bikes.add(keras.layers.Dense(75, activation='sigmoid'))
red_bikes.add(keras.layers.Dense(50, activation='sigmoid'))
red_bikes.add(keras.layers.Dense(1, activation='linear'))


In [231]:
#Vemos un resumen de la red
red_bikes.summary()


Model: "sequential_40"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 normalization_40 (Normaliza  (None, 15)               31        
 tion)                                                           
                                                                 
 dense_135 (Dense)           (None, 100)               1600      
                                                                 
 dense_136 (Dense)           (None, 75)                7575      
                                                                 
 dense_137 (Dense)           (None, 50)                3800      
                                                                 
 dense_138 (Dense)           (None, 1)                 51        
                                                                 
Total params: 13,057
Trainable params: 13,026
Non-trainable params: 31
________________________________________________

In [232]:
red_bikes.compile(optimizer='SGD', loss='mean_squared_error', metrics=['accuracy', 'mae'])
red_bikes.fit(attr_entrenamiento, obj_entrenamiento,
                batch_size=256, epochs=100)

Epoch 1/100
62/62 [==============================] - 1s 2ms/step - loss: 21364.1523 - accuracy: 0.0090 - mae: 103.0117
Epoch 2/100
62/62 [==============================] - 0s 2ms/step - loss: 3297.5176 - accuracy: 0.0090 - mae: 38.1368
Epoch 3/100
62/62 [==============================] - 0s 2ms/step - loss: 1477.1879 - accuracy: 0.0090 - mae: 25.1976
Epoch 4/100
62/62 [==============================] - 0s 2ms/step - loss: 728.1107 - accuracy: 0.0090 - mae: 16.0813
Epoch 5/100
62/62 [==============================] - 0s 2ms/step - loss: 457.1698 - accuracy: 0.0090 - mae: 13.5012
Epoch 6/100
62/62 [==============================] - 0s 2ms/step - loss: 215.3425 - accuracy: 0.0090 - mae: 9.1838
Epoch 7/100
62/62 [==============================] - 0s 2ms/step - loss: 192.7671 - accuracy: 0.0090 - mae: 9.6796
Epoch 8/100
62/62 [==============================] - 0s 2ms/step - loss: 244.7318 - accuracy: 0.0090 - mae: 9.0347
Epoch 9/100
62/62 [==============================] - 0s 2ms/step - los

In [233]:
red_bikes.evaluate(attr_prueba, obj_prueba)

55/55 [==============================] - 0s 1ms/step - loss: 60.8783 - accuracy: 0.0104 - mae: 5.5832


[60.878299713134766, 0.010356731712818146, 5.583206653594971]

In [242]:
#X=attr[2]
X=attr[10]
X = X.reshape((1, 15))

predicciones = red_bikes.predict(X)
print(predicciones)

1/1 [==============================] - 0s 22ms/step
[[36.13933]]


In [6]:
#Metodo LIME
import random
from sklearn.linear_model import Ridge



"""
N es el n´umero de permutaciones a realizar
f es el modelo a explicar
X′ ← {} muestras perturbadas
R ← {} representaciones
W ← {} las distancias entre la muestra x y sus perturbaciones
for 1
to
N do
Selecciona k atributos aleatoriamente
x′ ← una perturbaci´on de x donde se perturban los k atributos anteriores.
w ← la distancia entre x y x′
r ← la representaci´on de x′ respecto a x
X′ ← X′ ∪ x′
R ← R ∪ r
W ← R ∪ w
end for
Y ′ ← f(X′) las predicciones de las perturbaciones
G ← modelo ridge entrenado con R para predecir Y ′ y ponderando cada
muestra con W
return los par´ametros de G
"""

def explain_model(f, x, N,M):
    #f es el modelo a explicar
    #N es el número de permutaciones a realizar
    Xi = [] #muestras perturbadas
    R = [] #representaciones
    W = [] #Las distancias entre la muestra x y sus pertubaciones
    for i in range(N):
        k = random.randint(1, len(x)) #Escojo un número aletario que representa el número de los atributos a seleccionar
        perturbed_x = x.copy() #copio la muestra original
        for i in range(k): 
            perturbed_attr = random.choice(list(x.keys())) #Voy escojiento los atributos que perturbare de forma aleatoria
            mx = abs(max([a[perturbed_attr] for a in M])) #Para el atributo aletorio seleccionado calculo el valor máximo
            mn = abs(min([a[perturbed_attr] for a in M])) #Para el atributo aletorio seleccionado calculo el valor mínimo
            perturbed_x[perturbed_attr] = random.uniform(mn, mx) # pertubo el atributo con un valor aleatorio ente mn y mx
        w = abs(sum([x[attr] - perturbed_x[attr] for attr in x.keys()])) #Calculo la distancia entre el original y el perturbado
        r = {attr: 0  if x_perturbed[attr] = x[attr] else 1 for attr in x.keys()} #miramos la representacion del pertubado respecto al original utilizando un operador ternario como solemos hacer en java
        Xi.append(x_perturbed) #Acumulo en la lista los perturbados
        R.append(r)#Acumulamos en la lista de representaciones
        W.append(w)#Añadimos las distancias a la lista
    Y_perturbed = f(Xi)#aplicamos el modelo f
    G = Ridge().fit(R, Y_perturbed, sample_weight=W) #Utilizamos Ridge 
    return G.get_params() #Devolvemos los parametros


In [27]:
#METODO IDENTIDAD
import pandas
import numpy as np
from scipy.spatial.distance import cdist
from scipy.stats import pearsonr
from scipy.special import lambertw
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

# Creamos dos instancias de datos y sus respectivas explicaciones LIME
xa = np.array([0.5, 0.7, 0.1, 0.3])
xb = np.array([0.3, 0.9, 0.2, 0.1])
ea = np.array([0.2, 0.3, 0.1, 0.4])
eb = np.array([0.3, 0.4, 0.5, 0.1])

# Calculamos la distancia entre las instancias de datos
data_distance = cdist(xa.reshape(1,-1), xb.reshape(1,-1))

# Calculamos la distancia entre las explicaciones LIME
exp_distance = cdist(ea.reshape(1,-1), eb.reshape(1,-1))

# Verificamos si la métrica Identidad se cumple
if data_distance == 0 and exp_distance != 0:
    print("La métrica Identidad no se cumple para este par de instancias de datos y sus explicaciones LIME correspondientes.")
else:
    print("La métrica Identidad se cumple para este par de instancias de datos y sus explicaciones LIME correspondientes.")


La métrica Identidad se cumple para este par de instancias de datos y sus explicaciones LIME correspondientes.


In [ ]:
#METODO SEPARABILIDAD
# Creamos dos instancias de datos y sus respectivas explicaciones LIME
xa = np.array([0.5, 0.7, 0.1, 0.3])
xb = np.array([0.3, 0.9, 0.2, 0.1])
ea = np.array([0.2, 0.3, 0.1, 0.4])
eb = np.array([0.3, 0.4, 0.5, 0.1])

# Calculamos la distancia entre las instancias de datos
data_distance = cdist(xa.reshape(1,-1), xb.reshape(1,-1))

# Calculamos la distancia entre las explicaciones LIME
exp_distance = cdist(ea.reshape(1,-1), eb.reshape(1,-1))

# Verificamos si la métrica Separabilidad se cumple
if data_distance != 0 and exp_distance <= 0:
    print("La métrica Separabilidad no se cumple para este par de instancias de datos y sus explicaciones LIME correspondientes.")
else:
    print("La métrica Separabilidad se cumple para este par de instancias de datos y sus explicaciones LIME correspondientes.")


In [ ]:
#METODO ESTABILIDAD
# Creamos las instancias de datos y sus respectivas explicaciones LIME
x = np.array([[0.5, 0.7, 0.1, 0.3], [0.3, 0.9, 0.2, 0.1], [0.1, 0.2, 0.8, 0.6]])
ex = np.array([[0.2, 0.3, 0.1, 0.4], [0.3, 0.4, 0.5, 0.1], [0.1, 0.3, 0.6, 0.2]])

# Creamos las distancias entre las instancias de datos y sus respectivas explicaciones LIME
data_distances = cdist(x, x[0].reshape(1,-1))
exp_distances = cdist(ex, ex[0].reshape(1,-1))

# Calculamos el coeficiente de correlación de Pearson entre las distancias
correlation, _ = pearsonr(data_distances.flatten(), exp_distances.flatten())

# Verificamos si la métrica Estabilidad se cumple
if correlation > 0:
    print("La métrica Estabilidad se cumple para este conjunto de instancias de datos y sus explicaciones LIME correspondientes.")
else:
    print("La métrica Estabilidad no se cumple para este conjunto de instancias de datos y sus explicaciones LIME correspondientes.")


In [ ]:
#METODO COHERENCIA
# Creamos las instancias de datos y sus respectivas explicaciones LIME
x = np.array([[0.5, 0.7, 0.1, 0.3], [0.3, 0.9, 0.2, 0.1], [0.1, 0.2, 0.8, 0.6]])
ex = np.array([[0.2, 0.3, 0.1, 0.4], [0.3, 0.4, 0.5, 0.1], [0.1, 0.3, 0.6, 0.2]])

# Calculamos los pesos de las instancias de datos y sus respectivas explicaciones LIME
data_weights = np.exp(-np.linalg.norm(x - x.mean(axis=0), axis=1))
exp_weights = np.exp(-np.linalg.norm(ex - ex.mean(axis=0), axis=1))

# Calculamos los logaritmos naturales de los pesos y los sumamos
log_sum_data = np.sum(np.log(data_weights))
log_sum_exp = np.sum(np.log(exp_weights))

# Calculamos la métrica Coherencia
alpha = np.exp(log_sum_data - log_sum_exp + lambertw(0.0, -np.exp(log_sum_data - log_sum_exp)).real)
alpha /= len(x)

# Imprimimos el valor de la métrica Coherencia
print("El valor de la métrica Coherencia es:", alpha)


In [ ]:
#METODO COMPLETITUD
# Creamos las instancias de datos y sus respectivas explicaciones LIME
x = np.array([[0.5, 0.7, 0.1, 0.3], [0.3, 0.9, 0.2, 0.1], [0.1, 0.2, 0.8, 0.6]])
ex = np.array([[0.2, 0.3, 0.1, 0.4], [0.3, 0.4, 0.5, 0.1], [0.1, 0.3, 0.6, 0.2]])

# Calculamos los pesos de las instancias de datos y sus respectivas explicaciones LIME
data_weights = np.exp(-np.linalg.norm(x - x.mean(axis=0), axis=1))
exp_weights = np.exp(-np.linalg.norm(ex - ex.mean(axis=0), axis=1))

# Calculamos los valores de ei y pi
ei = np.sum(exp_weights)
pi = np.sum(data_weights)

# Calculamos la métrica Completitud
gamma = ei / pi

# Imprimimos el valor de la métrica Completitud
print("El valor de la métrica Completitud es:", gamma)


In [ ]:
#METODO CONGRUENCIA
# Creamos una lista de valores de coherencia para un conjunto de N muestras
alpha_values = [0.8, 0.6, 0.7, 0.9, 0.5]

# Calculamos el valor promedio de la coherencia
alpha = np.mean(alpha_values)

# Creamos una lista de valores de alpha_i para cada instancia de datos
alpha_i_values = [0.9, 0.7, 0.6, 0.8, 0.4]

# Calculamos el número de instancias de datos
N = len(alpha_i_values)

# Calculamos la suma de las diferencias cuadráticas entre alpha_i y alpha
diff_squares_sum = np.sum((np.array(alpha_i_values) - alpha) ** 2)

# Calculamos la métrica Congruencia
delta = np.sqrt((diff_squares_sum / N) / alpha)

# Imprimimos el valor de la métrica Congruencia
print("El valor de la métrica Congruencia es:", delta)


In [ ]:
#METODO SELECTIVIDAD
# Cargamos el dataset de cáncer de mama de scikit-learn
data = load_breast_cancer()

# Definimos las características y la variable objetivo
X = data['data']
y = data['target']

# Creamos un modelo de regresión logística
model = LogisticRegression()

# Entrenamos el modelo
model.fit(X, y)

# Obtenemos las predicciones del modelo en el conjunto de datos completo
y_pred = model.predict_proba(X)[:, 1]

# Calculamos el AUC para el modelo entrenado en el conjunto de datos completo
auc_full = roc_auc_score(y, y_pred)

# Ordenamos las características de más a menos relevantes según el modelo
idx_sorted = np.argsort(np.abs(model.coef_))[0][::-1]

# Creamos una lista para almacenar los AUC para cada característica eliminada
auc_scores = []

# Iteramos sobre las características de más a menos relevantes según el modelo
for i in range(X.shape[1]):
    # Establecemos la característica i en cero
    X_test = X.copy()
    X_test[:, idx_sorted[i]] = 0
    
    # Obtenemos las predicciones del modelo en el conjunto de datos con la característica i eliminada
    y_pred_test = model.predict_proba(X_test)[:, 1]
    
    # Calculamos el AUC para el modelo entrenado en el conjunto de datos con la característica i eliminada
    auc_test = roc_auc_score(y, y_pred_test)
    
    # Almacenamos el AUC para la característica i eliminada en la lista de AUC
    auc_scores.append(auc_test)

# Calculamos la métrica Selectividad como el área bajo la curva ROC para el gráfico de AUC vs características eliminadas
selectivity = np.trapz(auc_scores, dx=1)

# Imprimimos el valor de la métrica Selectividad
print("El valor de la métrica Selectividad es:", selectivity)
