In [179]:
#Importamos las librerias necesarias para crear la red neuronal
import pandas
import numpy as np
from sklearn import model_selection, preprocessing
from tensorflow import keras
import tensorflow as tf
#Leemos el csv
evaluation = pandas.read_csv('turkiye-student-evaluation_R_Specific.csv', header=0)

In [180]:
#Mostramos las 10 primeras lineas para ver que se ha leido bién
evaluation.head(10)

instr  class  nb.repeat  attendance  difficulty  Q1  Q2  Q3  Q4  Q5  ...  \
1       1      2          1           0           4   3   3   3   3   3  ...   
2       1      2          1           1           3   3   3   3   3   3  ...   
3       1      2          1           2           4   5   5   5   5   5  ...   
4       1      2          1           1           3   3   3   3   3   3  ...   
5       1      2          1           0           1   1   1   1   1   1  ...   
6       1      2          1           3           3   4   4   4   4   4  ...   
7       1      2          1           1           3   4   4   4   4   4  ...   
8       1      2          1           1           3   5   5   5   5   5  ...   
9       1      2          1           1           3   4   4   4   4   4  ...   
10      1      2          1           4           4   4   4   4   4   4  ...   

    Q19  Q20  Q21  Q22  Q23  Q24  Q25  Q26  Q27  Q28  
1     3    3    3    3    3    3    3    3    3    3  
2     3    3    3    3    3    3    3    3    3    3  
3     5    5    5    5    5    5    5    5    5    5  
4     3    3    3    3    3    3    3    3    3    3  
5     1    1    1    1    1    1    1    1    1    1  
6     4    4    4    4    4    4    4    4    4    4  
7     4    4    4    4    4    4    4    4    4    4  
8     5    5    5    5    5    5    5    5    5    5  
9     4    4    4    4    4    4    4    4    4    4  
10    4    4    4    4    4    4    4    4    4    4  

[10 rows x 33 columns]

In [181]:
#Seleccionamos los atributos 
atributos = evaluation.loc[:, 'class':'Q27']
atributos = atributos.to_numpy()
scaler = preprocessing.MinMaxScaler()
atributos = scaler.fit_transform(atributos)
print(atributos)

[[0.08333333 0.         0.         ... 0.5        0.5        0.5       ]
 [0.08333333 0.         0.25       ... 0.5        0.5        0.5       ]
 [0.08333333 0.         0.5        ... 1.         1.         1.        ]
 ...
 [1.         0.         0.         ... 1.         1.         1.        ]
 [1.         0.         0.25       ... 0.         0.         0.        ]
 [1.         0.         0.25       ... 0.         0.         0.        ]]


In [182]:
objetivo = evaluation['Q28']
objetivo = evaluation['Q28'].to_numpy(dtype=np.float32)
scaler = preprocessing.MinMaxScaler()
objetivo = scaler.fit_transform(objetivo.reshape(-1, 1))
print(objetivo)

[[0.5]
 [0.5]
 [1. ]
 ...
 [1. ]
 [0. ]
 [0. ]]


In [183]:
(atributos_entrenamiento, atributos_prueba,
 objetivo_entrenamiento, objetivo_prueba) = model_selection.train_test_split(
    atributos, objetivo, test_size=.15)

In [184]:
normalizador = keras.layers.Normalization()
normalizador.adapt(atributos_entrenamiento)
red_evaluation = keras.Sequential()
red_evaluation.add(keras.layers.Input(shape=(31,)))
red_evaluation.add(normalizador)
red_evaluation.add(keras.layers.Dense(75, activation='relu'))
red_evaluation.add(keras.layers.Dense(75, activation='sigmoid'))
red_evaluation.add(keras.layers.Dense(1, activation='sigmoid'))
red_evaluation.add(keras.layers.Lambda(lambda x: x * 5))


In [185]:
red_evaluation.summary()

Model: "sequential_26"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 normalization_26 (Normaliza  (None, 31)               63        
 tion)                                                           
                                                                 
 dense_97 (Dense)            (None, 75)                2400      
                                                                 
 dense_98 (Dense)            (None, 75)                5700      
                                                                 
 dense_99 (Dense)            (None, 1)                 76        
                                                                 
 lambda_2 (Lambda)           (None, 1)                 0         
                                                                 
Total params: 8,239
Trainable params: 8,176
Non-trainable params: 63
__________________________________________________

In [8]:

red_evaluation.compile(optimizer='SGD', loss='mean_squared_error', metrics=['accuracy', 'mae'])
red_evaluation.fit(atributos_entrenamiento, objetivo_entrenamiento,
                batch_size=256, epochs=10)

Epoch 1/10
20/20 [==============================] - 1s 4ms/step - loss: 0.2356 - accuracy: 0.2203 - mae: 0.3602
Epoch 2/10
20/20 [==============================] - 0s 2ms/step - loss: 0.0765 - accuracy: 0.3107 - mae: 0.2350
Epoch 3/10
20/20 [==============================] - 0s 3ms/step - loss: 0.0599 - accuracy: 0.3162 - mae: 0.2042
Epoch 4/10
20/20 [==============================] - 0s 4ms/step - loss: 0.0488 - accuracy: 0.3174 - mae: 0.1802
Epoch 5/10
20/20 [==============================] - 0s 4ms/step - loss: 0.0415 - accuracy: 0.3184 - mae: 0.1620
Epoch 6/10
20/20 [==============================] - 0s 3ms/step - loss: 0.0366 - accuracy: 0.3184 - mae: 0.1499
Epoch 7/10
20/20 [==============================] - 0s 3ms/step - loss: 0.0334 - accuracy: 0.3182 - mae: 0.1406
Epoch 8/10
20/20 [==============================] - 0s 4ms/step - loss: 0.0312 - accuracy: 0.3184 - mae: 0.1334
Epoch 9/10
20/20 [==============================] - 0s 4ms/step - loss: 0.0296 - accuracy: 0.3178 - mae:

In [9]:
red_evaluation.evaluate(atributos_prueba, objetivo_prueba)

28/28 [==============================] - 0s 703us/step - loss: 0.0315 - accuracy: 0.3322 - mae: 0.1270


[0.031479619443416595, 0.33218786120414734, 0.127012699842453]

In [3]:
#Importamos las librerias necesarias para crear la red neuronal
import pandas
import numpy as np
from sklearn import model_selection, preprocessing
from tensorflow import keras
import tensorflow as tf

#Leemos el csv
#bikes = pandas.read_csv('hour.csv', header=0)
bikes = pandas.read_csv('hour2.csv',header = 0)


In [4]:
#Mostramos las 10 primeras lineas para ver que se ha leido bién
bikes.head(10)

season  yr  mnth  hr  holiday  weekday  workingday  weathersit  temp  \
0       1   0     1   0        0        6           0           1  0.24   
1       1   0     1   1        0        6           0           1  0.22   
2       1   0     1   2        0        6           0           1  0.22   
3       1   0     1   3        0        6           0           1  0.24   
4       1   0     1   4        0        6           0           1  0.24   
5       1   0     1   5        0        6           0           2  0.24   
6       1   0     1   6        0        6           0           1  0.22   
7       1   0     1   7        0        6           0           1  0.20   
8       1   0     1   8        0        6           0           1  0.24   
9       1   0     1   9        0        6           0           1  0.32   

    atemp   hum  windspeed  casual  registered  cnt  
0  0.2879  0.81     0.0000       3          13   16  
1  0.2727  0.80     0.0000       8          32   40  
2  0.2727  0.80     0.0000       5          27   32  
3  0.2879  0.75     0.0000       3          10   13  
4  0.2879  0.75     0.0000       0           1    1  
5  0.2576  0.75     0.0896       0           1    1  
6  0.2727  0.80     0.0000       2           0    2  
7  0.2576  0.86     0.0000       1           2    3  
8  0.2879  0.75     0.0000       1           7    8  
9  0.3485  0.76     0.0000       8           6   14

In [6]:
#Seleccionamos los atributos y los nomalizamos
attr = bikes.loc[:, 'season':'registered']
attr = attr.to_numpy()
scaler = preprocessing.MinMaxScaler()
attr = scaler.fit_transform(attr)
print(attr)

[[0.         0.         0.         ... 0.         0.00817439 0.01467269]
 [0.         0.         0.         ... 0.         0.02179837 0.03611738]
 [0.         0.         0.         ... 0.         0.01362398 0.03047404]
 ...
 [0.         1.         1.         ... 0.19301751 0.01907357 0.09367946]
 [0.         1.         1.         ... 0.15786999 0.03542234 0.05417607]
 [0.         1.         1.         ... 0.15786999 0.03269755 0.04176072]]


In [7]:
#Seleccionamos los objetivos
obj = bikes['cnt']
obj = bikes['cnt'].to_numpy(dtype=np.float32)
#scaler = preprocessing.MinMaxScaler()
#objetivo = scaler.fit_transform(objetivo.reshape(-1, 1))
print(obj)

[16. 40. 32. ... 90. 61. 49.]


In [8]:
#Cogemos un 85% de los datos para entrenar y un 15% de los datos para evaluar el modelo
(attr_entrenamiento, attr_prueba,
 obj_entrenamiento, obj_prueba) = model_selection.train_test_split(
    attr, obj, test_size=.10)

In [13]:
#Creamos la red neuronal 
normalizador = keras.layers.Normalization()
normalizador.adapt(attr_entrenamiento)
red_bikes = keras.Sequential()
red_bikes.add(keras.layers.Input(shape=(14,))) #añadimos la capa de entrada con 14 neuronas
red_bikes.add(normalizador)#Aplicamos un normalizador
red_bikes.add(keras.layers.Dense(100, activation='sigmoid'))#Añadimos una capa intermedia de 100 neuronas con función de activación sigmoide
red_bikes.add(keras.layers.Dense(100, activation='sigmoid'))#Añadimos una capa intermedia de 100 neuronas con función de activación sigmoide
red_bikes.add(keras.layers.Dense(1, activation='linear'))#Necesitamos una capa de salida linear ya que los valores objetivos son lineares
#red_bikes.add(keras.layers.Lambda(lambda x: tf.cast(tf.round(x), dtype=tf.int32)))
#red_bikes.add(keras.layers.Lambda(lambda x: round(x)))


In [14]:
#Vemos un resumen de la red
red_bikes.summary()


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 normalization_2 (Normalizat  (None, 14)               29        
 ion)                                                            
                                                                 
 dense_6 (Dense)             (None, 100)               1500      
                                                                 
 dense_7 (Dense)             (None, 100)               10100     
                                                                 
 dense_8 (Dense)             (None, 1)                 101       
                                                                 
Total params: 11,730
Trainable params: 11,701
Non-trainable params: 29
_________________________________________________________________


In [16]:
#Compilamos y entrenamos la red neuronal, buscamos minimizar la función de perdida
red_bikes.compile(optimizer='SGD', loss='mean_squared_error', metrics=['accuracy', 'mae'])
red_bikes.fit(attr_entrenamiento, obj_entrenamiento,
                batch_size=256, epochs=10)

Epoch 1/10
62/62 [==============================] - 1s 2ms/step - loss: 139.3950 - accuracy: 0.0093 - mae: 9.3511
Epoch 2/10
62/62 [==============================] - 0s 2ms/step - loss: 135.1601 - accuracy: 0.0093 - mae: 9.1462
Epoch 3/10
62/62 [==============================] - 0s 2ms/step - loss: 108.3286 - accuracy: 0.0093 - mae: 6.4693
Epoch 4/10
62/62 [==============================] - 0s 2ms/step - loss: 87.2385 - accuracy: 0.0093 - mae: 6.1692
Epoch 5/10
62/62 [==============================] - 0s 2ms/step - loss: 75.5298 - accuracy: 0.0093 - mae: 6.7426
Epoch 6/10
62/62 [==============================] - 0s 2ms/step - loss: 82.9607 - accuracy: 0.0093 - mae: 6.9132
Epoch 7/10
62/62 [==============================] - 0s 2ms/step - loss: 76.4263 - accuracy: 0.0093 - mae: 7.0043
Epoch 8/10
62/62 [==============================] - 0s 2ms/step - loss: 83.1692 - accuracy: 0.0093 - mae: 7.1503
Epoch 9/10
62/62 [==============================] - 0s 2ms/step - loss: 42.1194 - accuracy: 0

In [17]:
#Definimos cuanta perdida queremos tener y ejecutamos el siguiente bucle para entrenar la red hasta conseguir una perdida menor a la definida
perdidaObj = 1.0
x=red_bikes.evaluate(attr_prueba, obj_prueba)
while x[0]>perdidaObj:
    red_bikes.fit(attr_entrenamiento, obj_entrenamiento,
                batch_size=256, epochs=10)
    x=red_bikes.evaluate(attr_prueba, obj_prueba)
    
print(x[0])

55/55 [==============================] - 0s 1ms/step - loss: 15.9997 - accuracy: 0.0069 - mae: 2.9485
Epoch 1/10
62/62 [==============================] - 0s 2ms/step - loss: 48.5767 - accuracy: 0.0093 - mae: 5.2197
Epoch 2/10
62/62 [==============================] - 0s 2ms/step - loss: 51.3548 - accuracy: 0.0093 - mae: 5.1844
Epoch 3/10
62/62 [==============================] - 0s 2ms/step - loss: 77.9876 - accuracy: 0.0093 - mae: 6.1130
Epoch 4/10
62/62 [==============================] - 0s 2ms/step - loss: 39.3891 - accuracy: 0.0093 - mae: 4.8097
Epoch 5/10
62/62 [==============================] - 0s 2ms/step - loss: 79.6484 - accuracy: 0.0093 - mae: 6.9759
Epoch 6/10
62/62 [==============================] - 0s 2ms/step - loss: 10.2278 - accuracy: 0.0093 - mae: 1.9573
Epoch 7/10
62/62 [==============================] - 0s 2ms/step - loss: 67.6278 - accuracy: 0.0090 - mae: 5.1665
Epoch 8/10
62/62 [==============================] - 0s 2ms/step - loss: 29.2602 - accuracy: 0.0093 - mae: 3

62/62 [==============================] - 0s 2ms/step - loss: 13.7107 - accuracy: 0.0093 - mae: 3.0958
Epoch 8/10
62/62 [==============================] - 0s 2ms/step - loss: 9.2692 - accuracy: 0.0093 - mae: 2.3891
Epoch 9/10
62/62 [==============================] - 0s 2ms/step - loss: 1.9228 - accuracy: 0.0093 - mae: 0.9866
Epoch 10/10
55/55 [==============================] - 0s 1ms/step - loss: 13.0901 - accuracy: 0.0069 - mae: 2.8658
Epoch 1/10
62/62 [==============================] - 0s 2ms/step - loss: 15.1803 - accuracy: 0.0093 - mae: 3.2894
Epoch 2/10
62/62 [==============================] - 0s 2ms/step - loss: 14.1880 - accuracy: 0.0093 - mae: 2.8422
Epoch 3/10
62/62 [==============================] - 0s 2ms/step - loss: 6.4843 - accuracy: 0.0093 - mae: 2.0497
Epoch 4/10
62/62 [==============================] - 0s 2ms/step - loss: 2.6636 - accuracy: 0.0093 - mae: 1.2241
Epoch 5/10
62/62 [==============================] - 0s 2ms/step - loss: 24.3431 - accuracy: 0.0090 - mae: 3.82

62/62 [==============================] - 0s 2ms/step - loss: 1.6653 - accuracy: 0.0093 - mae: 0.9453
Epoch 4/10
62/62 [==============================] - 0s 2ms/step - loss: 9.4421 - accuracy: 0.0091 - mae: 2.6209
Epoch 5/10
62/62 [==============================] - 0s 2ms/step - loss: 10.1389 - accuracy: 0.0093 - mae: 2.5118
Epoch 6/10
62/62 [==============================] - 0s 2ms/step - loss: 1.0197 - accuracy: 0.0093 - mae: 0.7321
Epoch 7/10
62/62 [==============================] - 0s 2ms/step - loss: 5.0332 - accuracy: 0.0093 - mae: 1.7855
Epoch 8/10
62/62 [==============================] - 0s 2ms/step - loss: 11.3207 - accuracy: 0.0090 - mae: 2.5510
Epoch 9/10
62/62 [==============================] - 0s 2ms/step - loss: 1.7467 - accuracy: 0.0093 - mae: 1.0437
Epoch 10/10
55/55 [==============================] - 0s 1ms/step - loss: 12.6455 - accuracy: 0.0069 - mae: 1.3844
Epoch 1/10
62/62 [==============================] - 0s 2ms/step - loss: 2.0230 - accuracy: 0.0093 - mae: 1.0804

In [210]:
#Ahora que ya hemos conseguido una perdida menor a la que queriamos, evaluamos para volver a comprobar que la hemos conseguido
red_bikes.evaluate(attr_prueba, obj_prueba)

55/55 [==============================] - 0s 1ms/step - loss: 0.8929 - accuracy: 0.0081 - mae: 0.6922


[0.8928684592247009, 0.00805523619055748, 0.6922006011009216]

In [20]:
#Ahora mismo comprobaremos manualmente si las predicciones de la red se parecen a lo que esperabamos utilizando los ultimos registros con los cuales no se ha entrenado

X=attr[17368]
predicciones = red_bikes.predict(X)
print('Esperado 203:',predicciones)
X=attr[17369]
predicciones = red_bikes.predict(X)
print('Esperado 247:',predicciones)
X=attr[17370]
predicciones = red_bikes.predict(X)
print('Esperado 315:',predicciones)
X=attr[17371]
predicciones = red_bikes.predict(X)
print('Esperado 214:',predicciones)
X=attr[17372]
predicciones = red_bikes.predict(X)
print('Esperado 164:',predicciones)
X=attr[17373]
predicciones = red_bikes.predict(X)
print('Esperado 122:',predicciones)
X=attr[17374]
predicciones = red_bikes.predict(X)
print('Esperado 119:',predicciones)
X=attr[17375]
predicciones = red_bikes.predict(X)
print('Esperado 89:',predicciones)
X=attr[17376]
predicciones = red_bikes.predict(X)
print('Esperado 90:',predicciones)
X=attr[17377]
predicciones = red_bikes.predict(X)
print('Esperado 61:',predicciones)
X=attr[17378]
predicciones = red_bikes.predict(X)
print('Esperado 49:',predicciones)

1/1 [==============================] - 0s 28ms/step
Esperado 203: [[203.3557]]
1/1 [==============================] - 0s 22ms/step
Esperado 247: [[246.93541]]
1/1 [==============================] - 0s 26ms/step
Esperado 315: [[315.41962]]
1/1 [==============================] - 0s 25ms/step
Esperado 214: [[215.09206]]
1/1 [==============================] - 0s 26ms/step
Esperado 164: [[164.07002]]
1/1 [==============================] - 0s 22ms/step
Esperado 122: [[121.828186]]
1/1 [==============================] - 0s 37ms/step
Esperado 119: [[119.20893]]
1/1 [==============================] - 0s 30ms/step
Esperado 89: [[89.70702]]
1/1 [==============================] - 0s 27ms/step
Esperado 90: [[90.72455]]
1/1 [==============================] - 0s 23ms/step
Esperado 61: [[62.387413]]
1/1 [==============================] - 0s 25ms/step
Esperado 49: [[48.95525]]


In [25]:
#Ahora trabajaremos con el otro modelo que será un random forest
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
forest_bikes = RandomForestRegressor()
forest_bikes.fit(attr_entrenamiento, obj_entrenamiento)
evaluaciones = forest_bikes.predict(attr_prueba)
mse = mean_squared_error(obj_prueba, evaluaciones)
print("Error cuadrático medio (MSE) del modelo:", mse)

Error cuadrático medio (MSE) del modelo: 3.8617047756041427


In [33]:
#Ahora mismo comprobaremos manualmente si las predicciones del random forest se parecen a lo que esperabamos utilizando los ultimos registros con los cuales no se ha entrenado
attr2 = attr[:, np.newaxis]
X=attr2[17368]
predicciones = forest_bikes.predict(X)
print('Esperado 203:',predicciones)
X=attr2[17369]
predicciones = forest_bikes.predict(X)
print('Esperado 247:',predicciones)
X=attr2[17370]
predicciones = forest_bikes.predict(X)
print('Esperado 315:',predicciones)
X=attr2[17371]
predicciones = forest_bikes.predict(X)
print('Esperado 214:',predicciones)
X=attr2[17372]
predicciones = forest_bikes.predict(X)
print('Esperado 164:',predicciones)
X=attr2[17373]
predicciones = forest_bikes.predict(X)
print('Esperado 122:',predicciones)
X=attr2[17374]
predicciones = forest_bikes.predict(X)
print('Esperado 119:',predicciones)
X=attr2[17375]
predicciones = forest_bikes.predict(X)
print('Esperado 89:',predicciones)
X=attr2[17376]
predicciones = forest_bikes.predict(X)
print('Esperado 90:',predicciones)
X=attr2[17377]
predicciones = forest_bikes.predict(X)
print('Esperado 61:',predicciones)
X=attr2[17378]
predicciones = forest_bikes.predict(X)
print('Esperado 49:',predicciones)

Esperado 203: [202.88]
Esperado 247: [246.91]
Esperado 315: [314.35]
Esperado 214: [214.84]
Esperado 164: [163.97]
Esperado 122: [122.11]
Esperado 119: [118.92]
Esperado 89: [89.09]
Esperado 90: [90.2]
Esperado 61: [61.13]
Esperado 49: [49.11]


In [ ]:
#Metodo LIME
import random
from sklearn.linear_model import Ridge



"""
N es el n´umero de permutaciones a realizar
f es el modelo a explicar
X′ ← {} muestras perturbadas
R ← {} representaciones
W ← {} las distancias entre la muestra x y sus perturbaciones
for 1
to
N do
Selecciona k atributos aleatoriamente
x′ ← una perturbaci´on de x donde se perturban los k atributos anteriores.
w ← la distancia entre x y x′
r ← la representaci´on de x′ respecto a x
X′ ← X′ ∪ x′
R ← R ∪ r
W ← R ∪ w
end for
Y ′ ← f(X′) las predicciones de las perturbaciones
G ← modelo ridge entrenado con R para predecir Y ′ y ponderando cada
muestra con W
return los par´ametros de G
"""

def explain_model(f, x, N,M):
    #f es el modelo a explicar
    #N es el número de permutaciones a realizar
    Xi = [] #muestras perturbadas
    R = [] #representaciones
    W = [] #Las distancias entre la muestra x y sus pertubaciones
    for i in range(N):
        k = random.randint(1, len(x)) #Escojo un número aletario que representa el número de los atributos a seleccionar
        perturbed_x = x.copy() #copio la muestra original
        for i in range(k): 
            perturbed_attr = random.choice(list(x.keys())) #Voy escojiento los atributos que perturbare de forma aleatoria
            mx = abs(max([a[perturbed_attr] for a in M])) #Para el atributo aletorio seleccionado calculo el valor máximo
            mn = abs(min([a[perturbed_attr] for a in M])) #Para el atributo aletorio seleccionado calculo el valor mínimo
            perturbed_x[perturbed_attr] = random.uniform(mn, mx) # pertubo el atributo con un valor aleatorio ente mn y mx
        w = abs(sum([x[attr] - perturbed_x[attr] for attr in x.keys()])) #Calculo la distancia entre el original y el perturbado
        r = {attr: 0  if x_perturbed[attr] = x[attr] else 1 for attr in x.keys()} #miramos la representacion del pertubado respecto al original utilizando un operador ternario como solemos hacer en java
        Xi.append(x_perturbed) #Acumulo en la lista los perturbados
        R.append(r)#Acumulamos en la lista de representaciones
        W.append(w)#Añadimos las distancias a la lista
    Y_perturbed = f(Xi)#aplicamos el modelo f
    G = Ridge().fit(R, Y_perturbed, sample_weight=W) #Utilizamos Ridge 
    return G.get_params() #Devolvemos los parametros


In [ ]:
#METODO IDENTIDAD
import pandas
import numpy as np
from scipy.spatial.distance import cdist
from scipy.stats import pearsonr
from scipy.special import lambertw
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

# Creamos dos instancias de datos y sus respectivas explicaciones LIME
xa = np.array([0.5, 0.7, 0.1, 0.3])
xb = np.array([0.3, 0.9, 0.2, 0.1])
ea = np.array([0.2, 0.3, 0.1, 0.4])
eb = np.array([0.3, 0.4, 0.5, 0.1])

# Calculamos la distancia entre las instancias de datos
data_distance = cdist(xa.reshape(1,-1), xb.reshape(1,-1))

# Calculamos la distancia entre las explicaciones LIME
exp_distance = cdist(ea.reshape(1,-1), eb.reshape(1,-1))

# Verificamos si la métrica Identidad se cumple
if data_distance == 0 and exp_distance != 0:
    print("La métrica Identidad no se cumple para este par de instancias de datos y sus explicaciones LIME correspondientes.")
else:
    print("La métrica Identidad se cumple para este par de instancias de datos y sus explicaciones LIME correspondientes.")


In [ ]:
#METODO SEPARABILIDAD
# Creamos dos instancias de datos y sus respectivas explicaciones LIME
xa = np.array([0.5, 0.7, 0.1, 0.3])
xb = np.array([0.3, 0.9, 0.2, 0.1])
ea = np.array([0.2, 0.3, 0.1, 0.4])
eb = np.array([0.3, 0.4, 0.5, 0.1])

# Calculamos la distancia entre las instancias de datos
data_distance = cdist(xa.reshape(1,-1), xb.reshape(1,-1))

# Calculamos la distancia entre las explicaciones LIME
exp_distance = cdist(ea.reshape(1,-1), eb.reshape(1,-1))

# Verificamos si la métrica Separabilidad se cumple
if data_distance != 0 and exp_distance <= 0:
    print("La métrica Separabilidad no se cumple para este par de instancias de datos y sus explicaciones LIME correspondientes.")
else:
    print("La métrica Separabilidad se cumple para este par de instancias de datos y sus explicaciones LIME correspondientes.")


In [ ]:
#METODO ESTABILIDAD
# Creamos las instancias de datos y sus respectivas explicaciones LIME
x = np.array([[0.5, 0.7, 0.1, 0.3], [0.3, 0.9, 0.2, 0.1], [0.1, 0.2, 0.8, 0.6]])
ex = np.array([[0.2, 0.3, 0.1, 0.4], [0.3, 0.4, 0.5, 0.1], [0.1, 0.3, 0.6, 0.2]])

# Creamos las distancias entre las instancias de datos y sus respectivas explicaciones LIME
data_distances = cdist(x, x[0].reshape(1,-1))
exp_distances = cdist(ex, ex[0].reshape(1,-1))

# Calculamos el coeficiente de correlación de Pearson entre las distancias
correlation, _ = pearsonr(data_distances.flatten(), exp_distances.flatten())

# Verificamos si la métrica Estabilidad se cumple
if correlation > 0:
    print("La métrica Estabilidad se cumple para este conjunto de instancias de datos y sus explicaciones LIME correspondientes.")
else:
    print("La métrica Estabilidad no se cumple para este conjunto de instancias de datos y sus explicaciones LIME correspondientes.")


In [ ]:
#METODO COHERENCIA
# Creamos las instancias de datos y sus respectivas explicaciones LIME
x = np.array([[0.5, 0.7, 0.1, 0.3], [0.3, 0.9, 0.2, 0.1], [0.1, 0.2, 0.8, 0.6]])
ex = np.array([[0.2, 0.3, 0.1, 0.4], [0.3, 0.4, 0.5, 0.1], [0.1, 0.3, 0.6, 0.2]])

# Calculamos los pesos de las instancias de datos y sus respectivas explicaciones LIME
data_weights = np.exp(-np.linalg.norm(x - x.mean(axis=0), axis=1))
exp_weights = np.exp(-np.linalg.norm(ex - ex.mean(axis=0), axis=1))

# Calculamos los logaritmos naturales de los pesos y los sumamos
log_sum_data = np.sum(np.log(data_weights))
log_sum_exp = np.sum(np.log(exp_weights))

# Calculamos la métrica Coherencia
alpha = np.exp(log_sum_data - log_sum_exp + lambertw(0.0, -np.exp(log_sum_data - log_sum_exp)).real)
alpha /= len(x)

# Imprimimos el valor de la métrica Coherencia
print("El valor de la métrica Coherencia es:", alpha)


In [ ]:
#METODO COMPLETITUD
# Creamos las instancias de datos y sus respectivas explicaciones LIME
x = np.array([[0.5, 0.7, 0.1, 0.3], [0.3, 0.9, 0.2, 0.1], [0.1, 0.2, 0.8, 0.6]])
ex = np.array([[0.2, 0.3, 0.1, 0.4], [0.3, 0.4, 0.5, 0.1], [0.1, 0.3, 0.6, 0.2]])

# Calculamos los pesos de las instancias de datos y sus respectivas explicaciones LIME
data_weights = np.exp(-np.linalg.norm(x - x.mean(axis=0), axis=1))
exp_weights = np.exp(-np.linalg.norm(ex - ex.mean(axis=0), axis=1))

# Calculamos los valores de ei y pi
ei = np.sum(exp_weights)
pi = np.sum(data_weights)

# Calculamos la métrica Completitud
gamma = ei / pi

# Imprimimos el valor de la métrica Completitud
print("El valor de la métrica Completitud es:", gamma)


In [ ]:
#METODO CONGRUENCIA
# Creamos una lista de valores de coherencia para un conjunto de N muestras
alpha_values = [0.8, 0.6, 0.7, 0.9, 0.5]

# Calculamos el valor promedio de la coherencia
alpha = np.mean(alpha_values)

# Creamos una lista de valores de alpha_i para cada instancia de datos
alpha_i_values = [0.9, 0.7, 0.6, 0.8, 0.4]

# Calculamos el número de instancias de datos
N = len(alpha_i_values)

# Calculamos la suma de las diferencias cuadráticas entre alpha_i y alpha
diff_squares_sum = np.sum((np.array(alpha_i_values) - alpha) ** 2)

# Calculamos la métrica Congruencia
delta = np.sqrt((diff_squares_sum / N) / alpha)

# Imprimimos el valor de la métrica Congruencia
print("El valor de la métrica Congruencia es:", delta)


In [ ]:
#METODO SELECTIVIDAD
# Cargamos el dataset de cáncer de mama de scikit-learn
data = load_breast_cancer()

# Definimos las características y la variable objetivo
X = data['data']
y = data['target']

# Creamos un modelo de regresión logística
model = LogisticRegression()

# Entrenamos el modelo
model.fit(X, y)

# Obtenemos las predicciones del modelo en el conjunto de datos completo
y_pred = model.predict_proba(X)[:, 1]

# Calculamos el AUC para el modelo entrenado en el conjunto de datos completo
auc_full = roc_auc_score(y, y_pred)

# Ordenamos las características de más a menos relevantes según el modelo
idx_sorted = np.argsort(np.abs(model.coef_))[0][::-1]

# Creamos una lista para almacenar los AUC para cada característica eliminada
auc_scores = []

# Iteramos sobre las características de más a menos relevantes según el modelo
for i in range(X.shape[1]):
    # Establecemos la característica i en cero
    X_test = X.copy()
    X_test[:, idx_sorted[i]] = 0
    
    # Obtenemos las predicciones del modelo en el conjunto de datos con la característica i eliminada
    y_pred_test = model.predict_proba(X_test)[:, 1]
    
    # Calculamos el AUC para el modelo entrenado en el conjunto de datos con la característica i eliminada
    auc_test = roc_auc_score(y, y_pred_test)
    
    # Almacenamos el AUC para la característica i eliminada en la lista de AUC
    auc_scores.append(auc_test)

# Calculamos la métrica Selectividad como el área bajo la curva ROC para el gráfico de AUC vs características eliminadas
selectivity = np.trapz(auc_scores, dx=1)

# Imprimimos el valor de la métrica Selectividad
print("El valor de la métrica Selectividad es:", selectivity)
